# ansible-playbook -i ubuntu-cluster/inventory.ini ubuntu-cluster/playbooks/remove/remove_ubuntu.yaml
---
- name: Удаление Ubuntu инстансов
  hosts: local
  tasks:

    - name: Удалить контейнеры
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - ubuntu1
        - ubuntu2
        - ubuntu3
        - ubuntu4
        - ubuntu5
