---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      # Удаляет лишние пробелы в конце строк
      - id: end-of-file-fixer
      # Добавляет символ конца файла
      - id: check-yaml

  - repo: https://github.com/ansible/ansible-lint
    rev: v24.7.0
    hooks:
      - id: ansible-lint
      # Использует Ansible Lint для проверки стиля и качества кода Ansible

  - repo: https://github.com/adrienverge/yamllint
    rev: 'v1.35.1'
    hooks:
      - id: yamllint
      # Автоматически проверяет YAML-файлы на соответствие стандартам
