# yamllint disable-line rule:line-length
# ansible-playbook -i ubuntu-cluster/inventory.ini ubuntu-cluster/playbooks/deploy/deploy_ubuntu.yaml
---
- name: Развертывание нескольких Ubuntu инстансов
  hosts: localhost
  vars_files:
    - vars.yaml

  tasks:
    - name: Сборка Docker образа
      community.docker.docker_image:
        name: my_custom_ubuntu_image
        source: build
        build:
          # yamllint disable-line rule:line-length
          path: /home/aeon/purpleschool/testing-environment/ubuntu-cluster/playbooks/deploy
          args:
            USERNAME: "{{ username }}"
            PASSWORD: "{{ password }}"
        state: present

    - name: Создание пользовательской сети Docker
      community.docker.docker_network:
        name: custom_network
        state: present

    - name: Запуск Ubuntu инстансов
      community.docker.docker_container:
        name: "{{ item }}"
        image: my_custom_ubuntu_image
        state: started
        published_ports:
          - "{{ ports[item] }}:22"
        env_file: .env
        networks:
          - name: custom_network
      loop:
        - ubuntu1
        - ubuntu2
        - ubuntu3
        - ubuntu4
        - ubuntu5
      vars:
        ports:
          ubuntu1: "2222"
          ubuntu2: "2223"
          ubuntu3: "2224"
          ubuntu4: "2225"
          ubuntu5: "2226"

# здесь можно добавить дополнительные задачи
# - name: Выполнение дополнительных конфигураций
#   debug:
#     msg: "Добавьте сюда задачи для конфигурации"
