# yamllint disable-line rule:line-length
# ansible-playbook -i ubuntu-service/inventory.ini ubuntu-service/playbooks/stop/stop_ubuntu.yaml
---
- name: Остановка Ubuntu инстансов
  hosts: local
  tasks:
    - name: Остановить контейнеры
      community.docker.docker_container:
        name: "{{ item }}"
        state: stopped
      loop:
        - ubuntu1
        - ubuntu2
        - ubuntu3
        - ubuntu4
        - ubuntu5
